"""Task Contract Layer — strict JSON contracts for inter-agent communication.

All communication between OpenClaw (planner/reviewer), Claude Code (executor),
and the Orchestrator (state machine) MUST use these structured formats.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field, asdict
from typing import Literal


# ─── Task Spec (OpenClaw → Claude Code) ──────────────────────


@dataclass(frozen=True)
class TaskSpec:
    """A single executable task generated by the planner."""

    task_id: str
    goal: str
    context: str
    files: list[str]
    constraints: list[str]
    success_criteria: list[str]

    def to_json(self) -> str:
        return json.dumps(asdict(self), indent=2, ensure_ascii=False)

    @classmethod
    def from_json(cls, raw: str) -> TaskSpec:
        data = json.loads(raw)
        return cls(**data)

    @classmethod
    def from_planner_output(cls, raw: str, task_id: str = "", goal: str = "") -> TaskSpec:
        """Parse loose planner output into a TaskSpec.

        Handles formats like:
            TASK: <description>
            FILES: <file1>, <file2>
            VERIFICATION: <how to verify>
        """
        task_desc = ""
        files: list[str] = []
        verification = ""

        for line in raw.strip().split("\n"):
            stripped = line.strip()
            upper = stripped.upper()
            if upper.startswith("TASK:"):
                task_desc = stripped.split(":", 1)[1].strip()
            elif upper.startswith("FILES:"):
                files_str = stripped.split(":", 1)[1].strip()
                files = [f.strip() for f in files_str.split(",") if f.strip()]
            elif upper.startswith("VERIFICATION:") or upper.startswith("VERIFY:"):
                verification = stripped.split(":", 1)[1].strip()

        if not task_desc:
            # Fallback: use first non-empty line as task
            for line in raw.strip().split("\n"):
                if line.strip():
                    task_desc = line.strip()[:500]
                    break

        return cls(
            task_id=task_id or "task_0",
            goal=goal,
            context=raw[:2000],
            files=files,
            constraints=[
                "preserve DOM IDs",
                "preserve CSS classes",
                "match existing code style",
                "minimum changes",
            ],
            success_criteria=[verification] if verification else ["tests pass"],
        )


# ─── Execution Result (Claude → Orchestrator) ────────────────


@dataclass
class ExecutionResult:
    """Result of Claude Code executing a task."""

    task_id: str
    status: Literal["success", "error", "timeout"]
    changes: list[str] = field(default_factory=list)
    diff_summary: str = ""
    test_result: Literal["pass", "fail", "skipped"] = "skipped"
    error_message: str = ""

    def to_json(self) -> str:
        return json.dumps(asdict(self), indent=2, ensure_ascii=False)

    @classmethod
    def from_json(cls, raw: str) -> ExecutionResult:
        data = json.loads(raw)
        return cls(**data)

    @property
    def is_success(self) -> bool:
        return self.status == "success"


# ─── Review Decision (OpenClaw → Orchestrator) ───────────────


@dataclass
class ReviewDecision:
    """Decision from the reviewer about an execution result."""

    decision: Literal["PASS", "FAIL"]
    reason: str
    next_action: Literal["continue", "repair", "replan", "abort"]

    def to_json(self) -> str:
        return json.dumps(asdict(self), indent=2, ensure_ascii=False)

    @classmethod
    def from_json(cls, raw: str) -> ReviewDecision:
        data = json.loads(raw)
        return cls(**data)

    @classmethod
    def from_reviewer_output(cls, raw: str) -> ReviewDecision:
        """Parse loose reviewer output into a ReviewDecision.

        Handles formats like:
            VERDICT: PASS or FAIL
            FEEDBACK: <text>
            ISSUES: <text>
        """
        verdict = "FAIL"
        feedback = ""
        issues = ""

        for line in raw.strip().split("\n"):
            stripped = line.strip()
            upper = stripped.upper()
            if upper.startswith("VERDICT:"):
                val = stripped.split(":", 1)[1].strip().upper()
                verdict = "PASS" if "PASS" in val else "FAIL"
            elif upper.startswith("FEEDBACK:"):
                feedback = stripped.split(":", 1)[1].strip()
            elif upper.startswith("ISSUES:"):
                issues = stripped.split(":", 1)[1].strip()

        if not feedback:
            feedback = raw[:300]

        if verdict == "PASS":
            next_action = "continue"
        elif issues and any(
            word in issues.lower() for word in ("critical", "security", "data loss")
        ):
            next_action = "replan"
        else:
            next_action = "repair"

        return cls(decision=verdict, reason=feedback, next_action=next_action)


# ─── Contract Validation ─────────────────────────────────────


class ContractError(Exception):
    """Raised when a contract is invalid."""


def validate_task_spec(data: dict) -> None:
    """Validate a TaskSpec dict. Raises ContractError on failure."""
    required = {"task_id", "goal", "context", "files", "constraints", "success_criteria"}
    missing = required - set(data.keys())
    if missing:
        raise ContractError(f"TaskSpec missing fields: {missing}")
    if not isinstance(data["files"], list):
        raise ContractError("TaskSpec.files must be a list")
    if not isinstance(data["constraints"], list):
        raise ContractError("TaskSpec.constraints must be a list")
    if not isinstance(data["success_criteria"], list):
        raise ContractError("TaskSpec.success_criteria must be a list")


def validate_execution_result(data: dict) -> None:
    """Validate an ExecutionResult dict. Raises ContractError on failure."""
    required = {"task_id", "status"}
    missing = required - set(data.keys())
    if missing:
        raise ContractError(f"ExecutionResult missing fields: {missing}")
    if data["status"] not in ("success", "error", "timeout"):
        raise ContractError(f"ExecutionResult.status invalid: {data['status']}")


def validate_review_decision(data: dict) -> None:
    """Validate a ReviewDecision dict. Raises ContractError on failure."""
    required = {"decision", "reason", "next_action"}
    missing = required - set(data.keys())
    if missing:
        raise ContractError(f"ReviewDecision missing fields: {missing}")
    if data["decision"] not in ("PASS", "FAIL"):
        raise ContractError(f"ReviewDecision.decision invalid: {data['decision']}")
    if data["next_action"] not in ("continue", "repair", "replan", "abort"):
        raise ContractError(f"ReviewDecision.next_action invalid: {data['next_action']}")
